#spring:

# datasource:
#    platform: mysql
#    url: jdbc:mysql://seokindb.cyw9yafkgtjp.ap-northeast-2.rds.amazonaws.com/TodayHouse_Test?autoReconnect=true
#    username:  seokin
#    password:  applemints77!
#    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전
#server:
#   port : 8080
spring:

  datasource:
    platform: mysql
    url: jdbc:mysql://bingsudb.cmjbj7d1h2du.ap-northeast-2.rds.amazonaws.com/BINGSUdb?autoReconnect=true&verifyServerCertificate=false&useSSL=false  # 변경해주세요
    username: master # 변경해주세요
    password: Kp191213 # 변경해주세요
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전
server:
  port: 9000

