spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://seokindb.cyw9yafkgtjp.ap-northeast-2.rds.amazonaws.com/TodayHouse?autoReconnect=true
    username:  seokin
    password:  applemints77!
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전
server :
  port : 8081